import Head from 'next/head'
import { GraphQLClient,  gql} from 'graphql-request'
import BlogCard from './components/BlogCard'

const graphcms = new GraphQLClient("https://us-east-1-shared-usea1-02.cdn.hygraph.com/content/clj7hvu360po401t28eea01fd/master");

const QUERY = gql`
{
  posts {
    id,
    title,
    slug,
    coverPhoto{
      url
    }
  }
}
`

export async function getStaticProps(){
  const {posts} = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({posts}) {
  return (
    <div>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />

    </Head>

    <main>
      {posts.map((post) => (
        <BlogCard title={post.title} 
        coverPhoto={post.coverPhoto} 
        slug={post.slug} 
        key={post.id}/>
      ))}
    </main>
    </div>
  )
}
